

DELETE FROM records;

DELETE FROM patients;

ALTER TABLE patients ADD COLUMN IF NOT EXISTS login VARCHAR NOT NULL;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS password BYTEA NOT NULL;
-- ALTER TABLE patients ALTER COLUMN password TYPR BYTEA USING passsword::bytea;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS role_id INTEGER NOT NULL;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS refresh_token VARCHAR;


DELETE FROM doctors;

ALTER TABLE doctors ADD COLUMN IF NOT EXISTS login VARCHAR NOT NULL;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS password BYTEA NOT NULL;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS role_id INTEGER NOT NULL;
ALTER TABLE doctors ADD COLUMN IF NOT EXISTS refresh_token VARCHAR;
